# Generated by Django 2.1 on 2020-08-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='products',
            old_name='desc',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='products',
            name='rating',
        ),
    ]
