# Generated by Django 2.1 on 2020-08-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200804_0013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart_items',
        ),
    ]
